services:
  trainomat:
    image: kdbhdm/trainomat:latest
    container_name: trainomat
    ports:
      - 8888:80
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=trainomat.bf-lernen.de
      - LETSENCRYPT_HOST=trainomat.bf-lernen.de
    networks:
      - internal
      - external

networks:
  external:
    name: external
    external: true
  internal:
    name: internal
    external: true

